"""Initial MYSQL

Revision ID: 01dd8023c726
Revises: 
Create Date: 2025-05-12 16:22:52.455789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dd8023c726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('institution', sa.Enum('POLYTECHNIC', 'UNIVERSITY', 'COLLEGE', 'OTHER', name='userinstitution'), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', 'SUSPENDED', 'UNVERIFIED', name='accountstatus'), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_status', ['account_status'], unique=False)

    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('ELECTRONICS', 'BOOKS', 'CLOTHING', 'ETC', name='itemcategory'), nullable=True),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR', name='itemcondition'), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'SOLD', name='itemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)

    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversation_item_sender', ['item_id', 'sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_sender_id'), ['sender_id'], unique=False)

    op.create_table('favourites',
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favourite_id'),
    sa.UniqueConstraint('user_id', 'item_id', name='_user_item_uc')
    )
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourites_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourites_user_id'), ['user_id'], unique=False)

    op.create_table('item_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('item_id', 'is_primary', name='uq_item_primary_image')
    )
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_index('idx_item_image_order', ['item_id', 'order'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_images_item_id'), ['item_id'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', 'FAILED', name='status'), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'MPESA', 'PAYPAL', 'BANK_TRANSFER', 'CRYPTO', name='paymentmethod'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_buyer_status', ['buyer_id', 'status'], unique=False)
        batch_op.create_index('idx_transaction_seller_status', ['seller_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_conversation_time', ['conversation_id', 'sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index('idx_message_conversation_time')

    op.drop_table('messages')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_seller_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_item_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_buyer_id'))
        batch_op.drop_index('idx_transaction_seller_status')
        batch_op.drop_index('idx_transaction_buyer_status')

    op.drop_table('transactions')
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_images_item_id'))
        batch_op.drop_index('idx_item_image_order')

    op.drop_table('item_images')
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourites_item_id'))

    op.drop_table('favourites')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_sender_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_item_id'))
        batch_op.drop_index('idx_conversation_item_sender')

    op.drop_table('conversations')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_seller_id'))

    op.drop_table('items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_user_email')

    op.drop_table('users')
    # ### end Alembic commands ###
