"""Fix relationship conflicts

Revision ID: 501443e2ca4c
Revises: 01dd8023c726
Create Date: 2025-05-13 14:39:49.737656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501443e2ca4c'
down_revision = '01dd8023c726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('student_id')
        batch_op.create_index(batch_op.f('ix_users_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_account_status'))
        batch_op.create_index('student_id', ['student_id'], unique=True)
        batch_op.create_index('idx_user_status', ['account_status'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
