"""Fix bidirectional relationship conflicts2

Revision ID: e1a9a4515c78
Revises: 501443e2ca4c
Create Date: 2025-05-13 14:54:29.364313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a9a4515c78'
down_revision = '501443e2ca4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_account_status')
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_status', ['account_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_user_email')
        batch_op.create_index('ix_users_account_status', ['account_status'], unique=False)

    # ### end Alembic commands ###
