name: Code Security Scan

on:
  push:
    branches: [dev, release, protect_release_branch]
  pull_request:
    branches: [dev, release]

jobs:
  codeql-analysis:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Analyze
        uses: github/codeql-action/analyze@v3